# Generated by Django 3.1.7 on 2021-08-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.subcategory', verbose_name='Подкатегория'),
        ),
    ]
