# Generated by Django 3.1.7 on 2021-08-10 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210803_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory2ndLvl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Подкатегория 2 уровень')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='URL')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория 2 уровень',
                'verbose_name_plural': 'Подкатегории 2 уровень',
            },
        ),
    ]
